---
# applied to all "load-balancers" machines
- hosts: load-balancers
  roles:
    # role is as a load balancer
    - role: load-balancer
      become: yes # execute as root

# applied to all "web-apps" machines
- hosts: web-apps
  roles:
    # role includes using node
    - role: node
      become: yes # execute as root
    # role also includes serving the hello world app
    - app-hello-world
