# Download the nodejs setup script from nodesource. This is following the official way to install
# node on AmazonLinux as it is not provided in the yum repositories.
- name: Download nodejs setup
  get_url:
    url: https://rpm.nodesource.com/setup_6.x
    dest: /nodejs-setup_6.x.sh
    mode: 0555
  register: get_node

# Run the nodejs setup script to add it to the yum package list. This step is skipped if the
# previous step to download node didn't result in a change.
- name: Add nodejs to yum repo
  command: /nodejs-setup_6.x.sh
  when: get_node|changed

# Ensure nodejs and git are installed on the system.
- name: Install packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - nodejs
    - git

# Install pm2, a nodejs process manager
- name: Install pm2
  npm:
    name: pm2
    global: yes
